server:
  port: 8503


spring:
  application:
    name: notification-service
  zipkin: 
    base-url: http://localhost:9411/
    
  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"
    
    
  rabbitmq:
    username: mehmetpekdemir
    password: mehmetpekdemir
    
    
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue
          

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/