apiVersion: v1
kind: Service
metadata:
  name: vehicle-api
  labels:
    app: vehicle-api
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: vehicle-api
  selector:
    app: vehicle-api