info:
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}
server:
  port: ${CONFIG_PORT:8081}
spring:
  application: #app discovery  config
    name: Vehicle-Service
eureka:
  datacenter: Main
  environment: Development
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_REGISTRY:localhost}:${EUREKA_REGISTRY_PORT:8761}/eureka
    registerWithEureka: false
    fetchRegistry: false
logging:
  level:
    com:
      netflix:
        eureka: "OFF"
        discovery: "OFF"
management:
  endpoints:
    web:
      exposure:
        include: "*"
    beans:
      cache:
        time-to-live: 10s
  health:
    show-details: "always"