server:
  port: 8199

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: Asdfgh12

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

